---
 - hosts: all
   roles:
    - isoft.common
    - isoft.php
    - ANXS.postgresql
    - isoft.nginx
   post_tasks:
    - name: Copy local configs
      template: >
        src=templates/symfony/parameters.yml.j2
        dest={{app_path}}/app/config/parameters.yml

 - hosts: vagrant
   roles:
    - isoft.composer
   post_tasks:
    - name: Prepare project
      shell: "{{item}} chdir={{app_path}}"
      sudo: true
      sudo_user: "{{app_user}}"
      with_items:
       - "composer install --prefer-dist --optimize-autoloader"
#       - "app/console doctrine:migrations:migrate --no-interaction"
