version: "2"

services:
    php:
        build: '.'
        depends_on:
            - database
        env_file: support/env/dev.env
        volumes:
            - '.:/srv'

    front:
        build: 'front'
        depends_on:
            - php
        ports:
            - 0.0.0.0:8080:80

    database:
        image: postgres:9.4
        env_file: support/env/dev.env
        volumes:
            - dbdata:/var/lib/postgresql

volumes:
    dbdata:
        driver: local
